imagePullSecrets:
  - name: docker-aiteza

aiteza:
  backendUrl: http://backend.local
  keycloak:
    url: http://auth.local
    realm: local
    clientId: test
  strapi:
    url: http://strapi.local
    secretRef:
      name: aiteza-strapi-secret

ingress:
  enabled: true
  ingresscClassName: traefik
  host: frontend.local
  tls:
    secretName: frontend-local-tls

securityContext: # in test
  runAsNonRoot: false
  runAsUser: 
  runAsGroup: 
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault