imagePullSecrets:
  - name: docker-aiteza

aiteza:
  audit:
    lokiUrl: http://localhost:3100
    secretRef:
      name: "aiteza-loki-secret"
  litellm:
    url: "https://litellm.local"
  chatNameModel: model1
  repromptModel: model1
  frontendOrigin: http://frontend.local
  database:
    postgres:
      host: database.local
      secretRef:
        name: aiteza-database-postgres-secret
  keycloak:
    authServerUrl: http://auth.local
    realm: local
    clientId: test
    secretRef:
      name: aiteza-keycloak-secret
  etl:
    firecrawl:
      secretRef:
        name: aiteza-etl-firecrawl-secret
    docling:
      baseUrl: http://docling.local
    tika:
      endpoint: http://tika.local
  search:
    reranking:
      enabled: true
      endpoint: "https://api.cohere.com/v2/rerank"
      model: "rerank-v3.5"
      secretRef:
        name: aiteza-search-reranking-secret
  models:
    model1:
      model: "gpt-4"
      name: "GPT-4"
      description: "OpenAI GPT-4 model"
      defaultModel: true
      enabled: true
      multiModal: false
      icon: "openai.svg"
      type: "chat"
      endpoint: "https://api.openai.com"
      chunks: 20
    model2:
      model: "gpt-3.5-turbo"
      name: "GPT-3.5 Turbo"
      description: "OpenAI GPT-3.5 Turbo model"
      defaultModel: false
      enabled: true
      selectable: false
      multiModal: false
      icon: "openai.svg"
      type: "chat"
      endpoint: "https://api.openai.com"
      chunks: 15

s3:
  enabled: true
  endpoint: https://s3.local
  region: eu-1
  bucketName: aiteza-bucket
  secretRef:
    name: aiteza-s3-secret
    keys: {}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://auth.local
  ai:
    openai:
      baseUrl: http://openai.local

springdoc:
  swaggerUi:
    oauth:
      clientId: test

environmentSecrets: []

ingress:
  enabled: true
  ingresscClassName: traefik
  host: backend.local
  tls:
    secretName: backend-local-tls

nodeSelector:
  run: application