imagePullSecrets:
  - name: docker-aiteza

aiteza:
  litellm:
    url: "https://litellm.local"
  chatNameModel: model1
  repromptModel: model1
  frontendOrigin: http://frontend.local
  database:
    postgres:
      host: database.local
      secretRef:
        name: aiteza-database-postgres-secret
  keycloak:
    authServerUrl: http://auth.local
    realm: local
    clientId: test
    secretRef:
      name: aiteza-keycloak-secret
  etl:
    firecrawl:
      secretRef:
        name: aiteza-etl-firecrawl-secret
      search:
        num-results: "5"
        timeout-in-seconds: "5000"
    docling:
      enabled: true
      baseUrl: http://docling.local
      convert-endpoint: "/v1/convert/file"
      convert-async-endpoint: "/v1/convert/source/async"
      result-endpoint: "/v1/result"
      status-endpoint: "/v1/status/poll"
      do-ocr: "true"
      ocr-engine: "easyocr"
      pdf-backend: "dlparse_v4"
      table-mode: "accurate"
      from-formats:
        - docx
        - pptx
        - html
        - image
        - pdf
        - md
        - csv
        - xlsx
        - audio
      vlm-pipeline-options:
        concurrency: "4"
        timeout: "240"
        scale: "2.0"
        temperature: "0.4"
    tika:
      endpoint: http://tika.local
  search:
    reranking:
      enabled: true
      endpoint: "https://api.cohere.com/v2/rerank"
      model: "rerank-v3.5"
      secretRef:
        name: aiteza-search-reranking-secret
    fullTextWeight: 0.7
  models:
    model1:
      model: "gpt-4"
      name: "GPT-4"
      description: "OpenAI GPT-4 model"
      defaultModel: true
      enabled: true
      multiModal: false
      icon: "openai.svg"
      type: "chat"
      endpoint: "https://api.openai.com"
      chunks: 20
    model2:
      model: "gpt-3.5-turbo"
      name: "GPT-3.5 Turbo"
      description: "OpenAI GPT-3.5 Turbo model"
      defaultModel: false
      enabled: true
      selectable: false
      multiModal: false
      icon: "openai.svg"
      type: "chat"
      endpoint: "https://api.openai.com"
      chunks: 15

s3:
  enabled: true
  endpoint: https://s3.local
  region: eu-1
  bucketName: aiteza-bucket
  secretRef:
    name: aiteza-s3-secret
    keys: {}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://auth.local
  ai:
    openai:
      baseUrl: http://openai.local

springdoc:
  swaggerUi:
    oauth:
      clientId: test

environmentSecrets: []

ingress:
  enabled: true
  ingresscClassName: traefik
  host: backend.local
  tls:
    secretName: backend-local-tls

nodeSelector:
  run: application